server:
  port: 8080

spring:
  application:
    name: coupon-template
  datasource:
    username: root
    password: lzm549468
    url: jdbc:mysql://192.168.31.88:3306/coupon?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver